// Define user roles
export const ROLES = {
  CITIZEN: 'CITIZEN',
  WORKER: 'WORKER',
  OFFICER: 'OFFICER',
  DEPT_HEAD: 'DEPT_HEAD',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  STATE_ADMIN: 'STATE_ADMIN',
  CENTRAL_ADMIN: 'CENTRAL_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};
